qubit_core:
  host: "host.lima.internal"
  grpc_port: 50051

perf_array_name: "NETWORK_EVENTS"

# Path to eBPF bytecode (overridden in K8s deployment)
ebpf_path: "/workspace/ebpf/target/bpfel-unknown-none/release/ebpf"