app:
  http_port: 9000
  grpc_port: 50051
  upstream: http://localhost:8080
db:
  host: localhost
  port: 8123
  user: default
  password: "qubit"
  table:
    ebpf_network_events: ebpf_network_events
kubernetes:
  in_cluster: true
  namespace: ""
  leader_election:
    enabled: true
    lease_duration: 15s
    renew_deadline: 10s
    retry_period: 2s