apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qubit.clusterAgent.fullname" . }}
  labels:
    app: {{ include "qubit.clusterAgent.fullname" . }}
    {{- include "qubit.labels" . | nindent 4 }}
